explorer:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:local_explorer}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:10}
  jobs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
